version: '3.8'

services:
  cassandra:
    image: 'bitnami/cassandra:4.1-debian-11'
    container_name: cassandra-server
    ports:
      - 127.0.0.1:7000:7000 # Cluster communication (7001 if SSL is enabled).
      - 127.0.0.1:9042:9042 # Native protocol client.
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra

volumes:
  cassandra_data:
    driver: local
