version: '3.7'

services:
  cassandra:
    image: 'docker.io/bitnami/cassandra:3-debian-10'
    container_name: cassandra-server
    ports:
      - 127.0.0.1:7000:7000
      - 127.0.0.1:9042:9042
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra

volumes:
  cassandra_data:
    driver: local
